//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEDM.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Compra
    {
        public int IdDetalle_Compra { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public int IdProducto { get; set; }
        public int IdCompras { get; set; }
        public Nullable<double> precioCompra { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
