//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionEDM.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public string IdDetalle_Venta { get; set; }
        public string Precio_venta { get; set; }
        public string Cantidad { get; set; }
        public string IdProducto { get; set; }
        public string IdVenta { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
